import clsx from "clsx";
import { ShieldCheck, Wifi } from "lucide-react";
import { SectionHeader, Card } from "../ui";
import type { AppSettings } from "../../types";

export function ClusterSettings({
  settings,
  setSettings,
  provName,
  setProvName,
  provPin,
  setProvPin,
  onAutoModeClick,
}: {
  settings: AppSettings;
  setSettings: (s: AppSettings) => void;
  provName: string;
  setProvName: (v: string) => void;
  provPin: string;
  setProvPin: (v: string) => void;
  onAutoModeClick: () => void;
}) {
  return (
    <div className="flex flex-col gap-4">
      {/* Cluster Mode */}
      <Card className="p-4">
        <SectionHeader
          icon={<ShieldCheck className="h-5 w-5 text-zinc-600 dark:text-zinc-300" />}
          title="Cluster Mode"
          subtitle="Manage how this device connects."
        />
        <div className="mt-4 flex flex-col gap-4 px-1">
          <div className="flex items-center gap-4 rounded-xl bg-zinc-900/5 p-1 dark:bg-white/5">
            <button
              className={clsx(
                "flex-1 rounded-lg py-1.5 text-sm font-medium transition",
                settings.cluster_mode === "auto"
                  ? "bg-white text-zinc-900 shadow-sm dark:bg-zinc-800 dark:text-zinc-50"
                  : "text-zinc-600 hover:bg-zinc-900/5 dark:text-zinc-400"
              )}
              onClick={onAutoModeClick}
            >
              Autogenerated
            </button>
            <button
              className={clsx(
                "flex-1 rounded-lg py-1.5 text-sm font-medium transition",
                settings.cluster_mode === "provisioned"
                  ? "bg-white text-zinc-900 shadow-sm dark:bg-zinc-800 dark:text-zinc-50"
                  : "text-zinc-600 hover:bg-zinc-900/5 dark:text-zinc-400"
              )}
              onClick={() => setSettings({ ...settings, cluster_mode: "provisioned" })}
            >
              Provisioned
            </button>
          </div>

          {settings.cluster_mode === "provisioned" && (
            <div className="flex flex-col gap-3 rounded-2xl border border-zinc-900/10 bg-white/50 p-4 dark:border-white/10 dark:bg-white/5">
              <div className="flex flex-col gap-1">
                <label className="text-xs font-medium text-zinc-600 dark:text-zinc-400">Cluster Name (No Spaces)</label>
                <input
                  className="h-10 rounded-xl border border-zinc-900/10 bg-white px-3 text-sm text-zinc-900 outline-none focus:ring-2 focus:ring-emerald-500/40 dark:border-white/10 dark:bg-zinc-950 dark:text-zinc-50"
                  value={provName}
                  onChange={(e) => setProvName(e.target.value.replace(/\s/g, ""))}
                />
                {provName.trim().includes(" ") && <span className="text-[10px] text-rose-500">Spaces not allowed.</span>}
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs font-medium text-zinc-600 dark:text-zinc-400">My Cluster PIN (Min 6 chars)</label>
                <input
                  className="h-10 rounded-xl border border-zinc-900/10 bg-white px-3 font-mono text-sm text-zinc-900 outline-none focus:ring-2 focus:ring-emerald-500/40 dark:border-white/10 dark:bg-zinc-950 dark:text-zinc-50"
                  value={provPin}
                  onChange={(e) => setProvPin(e.target.value.trim())}
                />
                {provPin.length > 0 && provPin.length < 6 && <span className="text-[10px] text-rose-500">PIN must be at least 6 characters.</span>}
                <span className="text-[11px] text-zinc-500 dark:text-zinc-400">
                  This PIN is local to this device — it's what other devices enter to pair <em>with</em> this one. Each device in a cluster keeps its own PIN; pairing doesn't share it.
                </span>
              </div>
            </div>
          )}

          {settings.cluster_mode === "auto" && (
            <div className="text-xs text-zinc-500">
              Cluster identity is randomly generated. To reset, use "Leave & Reset" in the header.
            </div>
          )}
        </div>
      </Card>

      <Card className="p-4">
        <SectionHeader
          icon={<Wifi className="h-5 w-5 text-zinc-600 dark:text-zinc-300" />}
          title="Discovery"
          subtitle="How this device is found."
        />
        <div className="mt-4 px-1">
          <div className="flex items-center justify-between">
            <div>
              <div className="text-sm font-medium text-zinc-900 dark:text-zinc-50">mDNS Advertising</div>
              <div className="text-xs text-zinc-500">Let other devices discover this one automatically. Turn off to stay hidden and connect only via Add Remote.</div>
            </div>
            <button
              onClick={() => setSettings({ ...settings, mdns_advertising: !settings.mdns_advertising })}
              className={clsx("relative h-6 w-11 shrink-0 rounded-full transition-colors", settings.mdns_advertising ? "bg-emerald-500" : "bg-zinc-200 dark:bg-zinc-700")}
            >
              <span className={clsx("block h-4 w-4 transform rounded-full bg-white shadow-sm transition-transform", settings.mdns_advertising ? "translate-x-6" : "translate-x-1")} />
            </button>
          </div>
        </div>
      </Card>
    </div>
  );
}
